// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type User struct {
	ID         int32          `json:"id"`
	Userid     string         `json:"userid"`
	Username   string         `json:"username"`
	Registered sql.NullBool   `json:"registered"`
	Language   sql.NullString `json:"language"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}
